### PR TITLE
Hadoop Assessment Tool updates

### PR DESCRIPTION
**Pull request by mmayekar**
1. Removed the force OS packages install from the script and added the commands in the readme.md which now the user will 
have to run to install OS package dependencies to satisfy requirements
2. Updated the shebang based on feedback

### CODE REVIEW

**Review by vasu2809 — CHANGES_REQUESTED** [review]
Hi - Can you please merge this PR changes into Version1 branch and not the main branch and send again for approval?

**Review by vasu2809 — CHANGES_REQUESTED** [review]
Hi - Can you please merge this PR changes into Version1 branch and not the main branch and send again for approval?

**Review by vasu2809 — CHANGES_REQUESTED** [review]
Hi - Can you please merge this PR changes into Version1 branch and not the main branch and send again for approval?

**Comment by mmayekar** [comment]
> Hi - Can you please merge this PR changes into Version1 branch and not the main branch and send again for approval?

Hi Vasu, I updated the base branch, now it should be pointing to version1. Thanks!

**Review by vasu2809 — APPROVED** [review]

**Review by vasu2809 — APPROVED** [review]

**Review by vasu2809 — APPROVED** [review]

**Pull request merged**
